swagger: "2.0"
info:
  description: "Simple API to test out OpenAPI"
  version: "1.0.0"
  title: "Sample API"
  contact:
    email: "someone@example.com"
  license:
    name: "User License"
    url: "http://www.example.com/licenses/LICENSE-2.0.html"
host: "example.com"
basePath: "/"
tags:
- name: "Greet"
  description: "Custom message to greet users"
  externalDocs:
    description: "Find out more"
    url: "https://en.wikipedia.org/wiki/Greeting"
schemes:
- "https"
- "http"
paths:
  /greet:
    get:
      tags:
      - "greet"
      summary: "Send a generic greeting to the world"
      description: ""
      operationId: "greetDefault"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
  /greet/{someone}:
    get:
      tags:
      - "greet"
      summary: "Send a greeting to someone"
      produces:
      - "application/json"
      parameters:
      - name: "someone"
        in: "path"
        description: "Someone to greet"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "OK"
